<?php

require_once("../../Config/Config.php");
require_once("VerificarAcceso.php");
require_once ($PathSGP . "/Lib/InicializarVariableGet.php");
require_once ($PathSGP . "/Lib/InicializarAdmin.php");
#Descomentar esta linea cuando se haga una actualización en Producción
#include('../MensajeMantenimiento.html'); die;

InicVarGetSimple("SoOrigenSolicitud");

?>

<!--
Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID: jqueryform-8befa4
Date: 2018-08-01 00:30:41
Generated by http://www.jqueryform.com
-->
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta name="generator" content="jqueryform.com">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Formulario de registro</title>
  
  <script src='https://www.google.com/recaptcha/api.js'></script>

  <script type="text/javascript">
      var onloadCallback = function() {
        
      };
  </script>
  <!-- Bootstrap -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/css/bootstrap-datepicker3.min.css" rel="stylesheet">
  

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href="vendor.css" rel="stylesheet">

<style type="text/css">
body{
  background-color: transparent;
}

.jf-form{
  margin-top: 28px;
}

.jf-form > form{
  margin-bottom: 32px;
}

.jf-option-box{
  display: none;
  margin-left: 8px;
}

.jf-hide{
  display: none;
}

.jf-disabled {
    background-color: #eeeeee;
    opacity: 0.6;
    pointer-events: none;
}

/* 
overwrite bootstrap default margin-left, because the <label> doesn't contain the <input> element.
*/
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
  position: absolute;
  margin-top: 4px \9;
  margin-left: 0px;
}

div.form-group{
  padding: 8px 8px 4px 8px;
}

.mainDescription{
  margin-bottom: 10px;
}

p{
 text-align:justify;
}

p.description{
  margin:0px;
}

.responsive img{
  width: 100%;
}

p.error, p.validation-error{
  padding: 5px;
}

p.error{
  margin-top: 10px;
  color:#a94442;
}

p.server-error{
  font-weight: bold;
}

div.thumbnail{
  position: relative;
  text-align: center;
}

div.thumbnail.selected p{
  color: #ffffff;
}

div.thumbnail .glyphicon-ok-circle{
  position: absolute;
  top: 16px;
  left: 16px;
  color: #ffffff;
  font-size: 32px;
}

.jf-copyright{color: #888888; display: inline-block; margin: 16px;display:none;}

.form-group.required .control-label:after {
    color: #dd0000;
    content: "*";
    margin-left: 6px;
}

.submit .btn.disabled, .submit .btn[disabled]{
  background: transparent;
  opacity: 0.75;
}

/* for image option with span text */
.checkbox label > span, .radio label > span{
  display: block;
}

.form-group.inline .control-label,
.form-group.col-1 .control-label,
.form-group.col-2 .control-label,
.form-group.col-3 .control-label
{
  display: block;
}

.form-group.inline div.radio,
.form-group.inline div.checkbox{
  display: inline-block;
}

.form-group.col-1 div.radio,
.form-group.col-1 div.checkbox{
  display: block;
}

.form-group.col-2 div.radio,
.form-group.col-2 div.checkbox{
  display: inline-flex;
  width: 48%;
}

.form-group.col-3 div.radio,
.form-group.col-3 div.checkbox{
  display: inline-flex;
  width: 30%;
}

.clearfix:after {
   content: ".";
   visibility: hidden;
   display: block;
   height: 0;
   clear: both;
}

</style>


</head>

<body>


<!-- ----------------------------------------------- -->
<div class="container jf-form">
<form data-licenseKey="" name="formulario" id="formulario" action='admin.php' method='post' enctype='multipart/form-data' novalidate autocomplete="on" onsubmit="return ComprobarDv()">
<input type="hidden" name="method" value="validateForm">
<input type="hidden" name="SoOrigenSolicitud" id="SoOrigenSolicitud"  value="<?php echo($SoOrigenSolicitud)?>"  >
<input type="hidden" id="serverValidationFields" name="serverValidationFields" value="">



<div class="form-group f29 " data-fid="f29">
  <label class="control-label sr-only" for="f29"></label>

	<div class="mainDescription">
		<div class='images'>
			<img src="../../Graficas/LogoOpciones.gif" alt="">
		</div>
	</div>


  
</div>




<div class="form-group f31 " data-fid="f31">
  <label class="control-label sr-only" for="f31"></label>

	<div class="mainDescription">
		<p><b> En esta sección usted puede formular las Peticiones, Quejas, Reclamos, Sugerencias y Denuncias sobre los temas de competencia de <?php echo $RazonSocial;?>. Registre los datos necesarios para responderle y el detalle de la solicitud.<br />
<br />
Los campos con <font color="red"> * </font> son obligatorios. </b></p>
	</div>


  
</div>


		<!--NOTA: CAMBIAR EL ENLACE DE POLITCA DE TRATAMIENTO DE DATOS, PARA EL CLIENTE CORRESPONDIENTE-->


<div class="form-group f33 required col-1" data-fid="f33">
  <label class="control-label sr-only" for="f33">Concentimiento</label>

	<div class="mainDescription">
		<p>Autorizo al <?php echo $RazonSocial ?> para dar tratamiento de mis datos personales registrados en el presente formulario, conforme a la Ley 1581 de 2012 y la política de tratamiento de datos personales, con la finalidad de otorgar una respuesta efectiva a su petición, queja, reclamo, sugerencia y denuncia, realizar encuestas de satisfacción y percepción sobre la entidad y realización de la caracterización de usuarios con el objetivo de focalizar estrategias de mejora en la atención de las solicitudes.<br />
<a href="https://antv.gov.co/index.php/component/jdownloads/send/1129-resoluciones-2017/5691-resolucion-2034-de-2017" target="_blank">Política de tratamiento de datos personales</a></p>
	</div>

<div class="checkbox">
  	<input  id="f33_1" name="f33[]"  type="checkbox" value="Autorizo" 
    data-rule-required="true"  >
  	<label  for="f33_1">
  		Autorizo
  	</label>
  </div>

  
</div>




<div class="form-group f5 required inline" data-fid="f5">
 
  <label class="control-label " for="f5" >Tipo de Solicitud</label>

	<div class="mainDescription">
		<p>Seleccione el tipo de solicitud de acuerdo a su necesidad.</p>
	</div>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-th-list"></i> </span>
<select class="form-control" id="f5" name="f5"   
    data-rule-required="true" onchange="TiposdescripSolicitudes();">
  <option  value="">- Select -</option>

  </select>
</div>

<div class="mainDescription" data-fid="fd1">
	<br>
  	<div class="mainDescription" id="fd1">
		<p></p>
	</div>

</div>
  
</div>

 <script>
  		
	  function ShowSelected(){
	  var cod = document.getElementById("f5").value;
	  /*alert(cod);*/
	  return cod;
	  }
	  console.log(ShowSelected());	  
  </script>

<div class="form-group f7 required inline" data-fid="f7">
  <label class="control-label" for="f7">Usuario Anónimo</label>

	<div class="mainDescription">
		<p>Seleccione si quiere o no registrar su información personal de contacto.</p>
	</div>

    <div class="radio">
  	    <input  id="f7_1" name="f7"  type="radio" value="SI" 
    data-rule-required="true" >
  	    <label  for="f7_1">
  		Sí
  	    </label>
    </div>

    <div class="radio">
  	    <input  id="f7_2" name="f7"  type="radio" value="NO">
  	    <label  for="f7_2">
  		No
  	    </label>
    </div>

</div>



<div class="form-group f39  jf-hide" data-fid="f39">
  <label class="control-label" for="f39"></label>

	<div class="mainDescription">
		<p>En caso que usted decida hacer uso del derecho consagrado en el parágrafo de artículo 4 de la Ley 1712 de 2015: “Cuando el usuario considere que la solicitud de la información pone en riesgo su integridad o la de su familia, podrá solicitar ante el Ministerio Público el procedimiento especial de solicitud con identificación reservada.” <br />
Se podrá acceder a la página de la Procuraduría General de la República a través del siguiente enlace:<br />
<a href="https://www.procuraduria.gov.co/SedeElectronica" target="_blank">Sede Electrónica Procuraduría General de la República</a></p>
	</div>


  
</div>




<div class="form-group f40 required " data-fid="f40">
  <label class="control-label" for="f40">Tipo de Solicitante</label>

	<div class="mainDescription">
		<p>Seleccione el tipo de solicitante.</p>
	</div>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-th-list"></i> </span>
<select class="form-control" id="f40" name="f40"   
    data-rule-required="true" onchange="TiposdescripSolicitudes();">
    <option  value="">- Select -</option>
  </select>
</div>
  
</div>

	
<script>
function ShowSelected(){
    var cod = document.getElementById("f40").value;
	
    return cod;
}</script>
<?php
$TlId = "<script>
function ShowSelected2(){
    var cod = ShowSelected();
}</script>";

echo "TlId = "  . "$TlId";
			
/*if ($TlId == 'PN'){

	echo "lalala";
	
} else {
    
	echo "197287372";

	
}*/
?>




<div class="form-group f43 required " data-fid="f43">
  <label class="control-label" for="f43">Persona</label>

	<div class="mainDescription">
		<p>Seleccione el tipo de persona.</p>
	</div>

<!--Se cambia 'ratio element' a lista desplegable-->

<div class="input-group">
	<span class="input-group-addon left">
		<i class="glyphicon glyphicon-th-list"></i>
	</span>
		<select class="form-control" name="f43" id="f43" data-rule-required="true" required>
			<option value="">- Select -</option>
		</select>
</div>

</div>






<div class="form-group f11 required " data-fid="f11">
  <label class="control-label" for="f11">Tipo de Identificación</label>

	<div class="mainDescription">
		<p>Seleccione el tipo de identificación.</p>
	</div>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-th-list"></i> </span>
<select class="form-control" id="f11" name="f11"   
    data-rule-required="true" >
  <option  value="">- Select -</option>
 
  </select>
</div>
  
</div>



<div class="form-group f25 required " data-fid="f25">
  <label class="control-label" for="f25">Número de Identificación</label>

    <div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-th"></i> </span>
        <input type="text" class="form-control" id="f25" name="f25" value="" maxlength="10" data-rule-required="true" data-rule-maxlength="10" data-mask="#"/>
    </div>

  
</div>

  
<!--
CAMPO CREADO PARA NIT
-->

<div class="form-group fn25 required jf-hide" data-fid="fn25">
<div class="col-xs-12 col-md-6">
  <label class="control-label" for="fn25">Nro. de Identificación NIT</label>

    <div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-th"></i> </span>
        <input type="text" class="form-control" id="fn25" name="fn25" value="" maxlength="10" required data-rule-required="true" data-rule-maxlength="10" data-mask="#" onchange="ShowNit();"/>
        <span class="input-group-addon">-</span>
        <input name="dv" id="dv" type="text" required class="form-control" placeholder="DV" value="" maxlength="1" data-rule-required="true" data-rule-maxlength="1" data-mask="#" onchange="ComprobarDv();">
    </div><br />

  
</div>
</div>









<!-- ----------------------------------------------- -->

<script src="validateNIT.js" ></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/locales/bootstrap-datepicker.es.min.js"></script>
<script type="text/javascript">
	$.fn.datepicker.defaults.language = 'es';
</script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
<script src="vendor.js" ></script>

<script src="jqueryform.com.min.js?ver=v2.1.3&id=formulario" ></script>




<!-- [ Start: iCheck support ] ---------------------------------- -->
<link href="https://cdn.jsdelivr.net/icheck/1.0.2/skins/flat/_all.min.css" rel="stylesheet">
<style type="text/css">
/* overwrite bootstrap styles */
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
    position: relative;
    margin-top: 0px;
    margin-left: 2px;
}

.checkbox label, .radio label {
   padding-left: 4px;
}

</style>

<script src="https://cdn.jsdelivr.net/icheck/1.0.2/icheck.min.js"></script>
<script type="text/javascript">


;(function ($, undefined)
{

var checkers = '.icheckbox_flat, .iradio_flat';

function initICheck( $input ){
  $input.iCheck({
	    checkboxClass: 'icheckbox_flat',
	    radioClass: 'iradio_flat'
  }).on('ifClicked', function(e){
    setTimeout( function(){
      $(e.target).valid();
      $(e.target).trigger('change').trigger('handleOptionBox');
    }, 250);
  });
}; // func

//$('.jf-form .checkbox, .jf-form .radio')
$('.jf-form input[type="checkbox"], .jf-form input[type="radio"]').each( function( i, e ){
    var $input = $(e), $div = $input.closest('.checkbox,.radio'), hasImg = $div.find('label > img').length;
    if( hasImg ){

        $input.css({ 'opacity': '0', 'position': 'absolute', 'left': '-1000px', 'right': '-1000px'} );

    }else{

        initICheck( $input );

        // IE11 and under, the table-cell makes the checkboxes/radio buttons not clickable
        var isWin = navigator.platform.indexOf('Win') > -1,
            isEdge = navigator.userAgent.indexOf('Edge/') > -1,
            noTableCell = isWin && !isEdge;
        if( !noTableCell ){
          $div.find('label').css( { display: 'table-cell' } );
          $(checkers).css( { display: 'table-cell' } );
        };

    };
});

})(jQuery);

</script>
<!-- [ End: iCheck support ] ---------------------------------- -->


<!-- [ Start: Select2 support ] ---------------------------------- -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.full.min.js"></script>
<style type="text/css">
.select2-hidden-accessible{
	opacity: 0;
    width:1% !important;
}
.select2-container .select2-selection--single{
  height: 34px;
  padding-top: 2px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  border: 1px solid #ccc;
}
.select2-container--default .select2-selection--single .select2-selection__arrow{
  top: 4px;
}
</style>
<script type="text/javascript">
;(function(){
	
	function templateResult (obj) {
	  if (!obj.id) { return obj.text; }

	  var img = $(obj.element).data('imgSrc');
	  if( img ){
	    return $( '<span><img src="' + img + '" class="img-flag" /> ' + obj.text + '</span>' );
	  };

	  return obj.text;
	};
	 
	$(".jf-form select").css('width', '100%'); // make it responsive
	$(".jf-form select").select2({
	  templateResult: templateResult
	}).change( function(e){
	  $(e.target).valid();
	});

})();
</script>
<!-- [ End: Select2 support ] ---------------------------------- -->


<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.3.6/js/locales/es.min.js"></script>
<script src="CargaListas.js"></script>
<script src="<?php echo ($UrlSGP) ?>/Ajax/Json.js"></script>
<!--// tell jquery fileinput plugin init with selected lanaguage-->
<script>
fileinputLanguage = 'es';
</script>


<script type="text/javascript">


</script>

  </body>
</html>